version: 2
jobs:
  build:
    working_directory: ~/kenticokontentnuxtmodule
    docker:
      - image: circleci/node:16.13.0
    steps:
      # Checkout repository
      - checkout

      - run:
          name: Check current version of node
          command: node -v

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # build
      - run: yarn build

      # Test
      # - run: yarn test
      
      # Release 
      - run:
          name: release
          command: npm run semantic-release || true
          secrets: [ npm_token, gh_token ]